/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class Absen extends javax.swing.JPanel {
    private Statement st;
    private Connection Con;
    private ResultSet Rs;
    private String Sql="";
    /**
     * Creates new form Absen
     */
    public Absen() {
        initComponents();
        displayData();
    }
    private void displayData() {
        try {
            Con = Koneksi.getConnection();
            st = Con.createStatement();
            Tampil(Sql);  
        } catch (Exception e) {
            System.out.println("Koneksi Gagal" + e.getMessage());
        }
    }
    private void Tampil(String Sql) {
        DefaultTableModel kolomkolom = new DefaultTableModel();
        kolomkolom.addColumn("ID Karyawan");
        kolomkolom.addColumn("Nama Karyawan");
        kolomkolom.addColumn("Posisi");
        kolomkolom.addColumn("Tanggal");
        kolomkolom.addColumn("Waktu Absen");
        kolomkolom.addColumn("Keterangan");


        try {
            st = Con.createStatement();
            Rs = st.executeQuery("SELECT * FROM tbabsen1");
            while (Rs.next()) {
                kolomkolom.addRow(new Object[] {
                    Rs.getString(2), Rs.getString(3), Rs.getString(4),
                    Rs.getString(5), Rs.getString(6), Rs.getString(7)});
            }
            Tabelabsen.setModel(kolomkolom);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan \n" + e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabelabsen = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1520, 680));

        Tabelabsen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Karyawan", "Nama Karyawan", "Posisi", "Tanggal", "Waktu Absen"
            }
        ));
        jScrollPane1.setViewportView(Tabelabsen);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 204, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ABSEN KARYAWAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        );

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1513, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        String scannedBarcode = jTextField1.getText(); // Mengambil nilai dari JTextField
        updateKeterangan(scannedBarcode);
        jTextField1.setText("");  // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    private void updateKeterangan(String scannedBarcode) {
    try {
        Con = Koneksi.getConnection();
        st = Con.createStatement();
        String updateSql = "UPDATE tbabsen1 SET Keterangan = 'Hadir' WHERE ID_Karyawan = '" + scannedBarcode + "'";
        st.executeUpdate(updateSql);
        Tampil(Sql); // Memperbarui tampilan tabel setelah pembaruan database
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal melakukan pembaruan keterangan\n" + e);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabelabsen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
