/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaapplication1;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ButtonGroup;

/**
 *
 * @author LENOVO
 */
public class Data extends javax.swing.JPanel {
    private Statement st;
    private ResultSet Rs;
    private String Sql="";
    private Connection Con; 
    private DefaultTableModel model;
    private ButtonGroup jenisKelaminGroup;
    
    

    /**
     * Creates new form Data
     * @param 
     */
    
    public Data() {
     try {
        Con = Koneksi.getConnection();
        st = Con.createStatement();
    } catch (SQLException ex) {
        throw new RuntimeException("Error saat terhubung ke database: " + ex.getMessage(), ex);
    }
        initComponents();
        Tampil();
      
        
        jenisKelaminGroup = new ButtonGroup();
        jenisKelaminGroup.add(Laki);
        jenisKelaminGroup.add(Perempuan);
    }
    private void Tampil() {
        DefaultTableModel kolomkolom = new DefaultTableModel();
        kolomkolom.addColumn("ID Karyawan");
        kolomkolom.addColumn("Nama Karyawan");
        kolomkolom.addColumn("Alamat");
        kolomkolom.addColumn("Posisi");
        kolomkolom.addColumn("Jenis Kelamin");
        kolomkolom.addColumn("Nomor HP");
        
        kolomkolom.getDataVector().removeAllElements();
        kolomkolom.fireTableDataChanged();
        kolomkolom.setRowCount(0);

        try {
            st = Con.createStatement();
            Rs = st.executeQuery("SELECT * FROM tbcrew");
            while (Rs.next()) {
                 Object[] data = {
                    Rs.getString(1), Rs.getString(2), Rs.getString(3),
                    Rs.getString(4), Rs.getString(5),Rs.getString(6)};
                kolomkolom.addRow(data); 
                Tabeldata.setModel(kolomkolom);
                
            }
          
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan \n" + e);
        }
    }
    private void Refresh(){
        Nama.setText("");
        Alamat.setText("");
        Posisi.setSelectedIndex(0);
        NomorHp.setText("");
        jenisKelaminGroup.clearSelection();
        
        simpan.setText("Simpan");
    }
    private boolean checkIDExist(String idKaryawan) {
    try {
        Connection con = (Connection) Koneksi.getConnection();
        String query = "SELECT * FROM tbcrew WHERE `ID Karyawan`=?";
        PreparedStatement pat = con.prepareStatement(query);
        pat.setString(1, idKaryawan);
        ResultSet rs = pat.executeQuery();
        return rs.next(); // Jika rs.next() mengembalikan true, berarti ID sudah ada
    } catch (SQLException e) {
        e.printStackTrace();
        return false;
    }
}

     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Perempuan = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        hapus = new javax.swing.JButton();
        Laki = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        NomorHp = new java.awt.TextField();
        Alamat = new java.awt.TextField();
        Nama = new java.awt.TextField();
        simpan = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Posisi = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabeldata = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA KARYAWAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("POSISI");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 60, 16));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NOMOR HP");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, 16));

        Perempuan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Perempuan.setForeground(new java.awt.Color(255, 255, 255));
        Perempuan.setText("Perempuan");
        Perempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerempuanActionPerformed(evt);
            }
        });
        jPanel3.add(Perempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("JENIS KELAMIN");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 110, 16));

        hapus.setBackground(new java.awt.Color(102, 255, 255));
        hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hapus.setText("Hapus Data");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel3.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 160, 30));

        Laki.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Laki.setForeground(new java.awt.Color(255, 255, 255));
        Laki.setText("Laki-laki");
        Laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LakiActionPerformed(evt);
            }
        });
        jPanel3.add(Laki, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 98, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ALAMAT");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, 16));
        jPanel3.add(NomorHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 270, -1));

        Alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatActionPerformed(evt);
            }
        });
        jPanel3.add(Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 270, -1));

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        jPanel3.add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 270, -1));

        simpan.setBackground(new java.awt.Color(51, 255, 51));
        simpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel3.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 150, 30));

        batal.setBackground(new java.awt.Color(255, 102, 102));
        batal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        jPanel3.add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 130, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NAMA");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 60, 16));

        Posisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "===========>Pilih Posisi<===========", "Leader", "Kashier", "Platting", "Kitchen" }));
        Posisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PosisiActionPerformed(evt);
            }
        });
        jPanel3.add(Posisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 270, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/1a8a1eae-5d2f-4756-b4b0-19b8389bb943.jpg"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 380));

        Tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Karyawan", "Nama Karyawan", "Posisi", "Jenis Kelamin", "Tanggal Absensi dan Waktu Absensi", "Keterangan", "Nomor HP"
            }
        )
        {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        }
    );
    Tabeldata.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            TabeldataMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(Tabeldata);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE))
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void PerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerempuanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
      int selectedRow = Tabeldata.getSelectedRow();
        if (selectedRow != -1) {
            String idKaryawan = Tabeldata.getValueAt(selectedRow, 0).toString();

            int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    String sql = "DELETE FROM tbcrew WHERE `ID Karyawan`=?";
                    Connection con = (Connection) Koneksi.getConnection();
                    PreparedStatement pat = con.prepareStatement(sql);
                    pat.setString(1, idKaryawan);
                    pat.executeUpdate();
                    DefaultTableModel model = (DefaultTableModel) Tabeldata.getModel();
                    model.removeRow(selectedRow);
                    Refresh();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void LakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LakiActionPerformed

    private void AlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatActionPerformed

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        String jk = null;
        String idPrefix = "";

        if (Laki.isSelected()) {
            jk = "Laki-Laki";
            idPrefix = "01";
        } else if (Perempuan.isSelected()) {
            jk = "Perempuan";
            idPrefix = "02";
        }

        try {
            String nama = Nama.getText();
            String posisi = (String) Posisi.getSelectedItem();
            String nomorHp = NomorHp.getText();
            String alamat = Alamat.getText();

            String hurufPertamaNama = nama.substring(0, 1).toUpperCase() + nama.substring(1);
            String hurufPertamaAlamat = alamat.substring(0, 1).toUpperCase() + alamat.substring(1);
            String hurufPertama = posisi.substring(0, 1).toUpperCase();
            String hurufKetiga = posisi.length() >= 3 ? posisi.substring(2, 3).toUpperCase() : "";
            String duaDigitTerakhir = nomorHp.length() >= 2 ? nomorHp.substring(nomorHp.length() - 2) : "";

            String IDKaryawan = hurufPertama + hurufKetiga + idPrefix + duaDigitTerakhir;

            // Cek apakah ID Karyawan sudah ada di tabel
            boolean isIDExist = checkIDExist(IDKaryawan);

            if (isIDExist) {
                String updateSql = "UPDATE tbcrew SET `Nama Karyawan`=?, `Alamat`=?, `Posisi`=?, `Jenis Kelamin`=?, `Nomor HP`=? WHERE `ID Karyawan`=?";
                Connection con = (Connection) Koneksi.getConnection();
                PreparedStatement updatePat = con.prepareStatement(updateSql);
                updatePat.setString(1, hurufPertamaNama);
                updatePat.setString(2, hurufPertamaAlamat);
                updatePat.setString(3, posisi);
                updatePat.setString(4, jk);
                updatePat.setString(5, nomorHp);
                updatePat.setString(6, IDKaryawan);
                updatePat.executeUpdate();
            } else {
                String insertSql = "INSERT INTO tbcrew(`ID Karyawan`, `Nama Karyawan`,`Alamat`, `Posisi`, `Jenis Kelamin`, `Nomor HP`) VALUES (?, ?, ?, ?, ?, ?)";
                Connection con = (Connection) Koneksi.getConnection();
                PreparedStatement insertPat = con.prepareStatement(insertSql);
                insertPat.setString(1, IDKaryawan);
                insertPat.setString(2, hurufPertamaNama);
                insertPat.setString(3, hurufPertamaAlamat);
                insertPat.setString(4, posisi);
                insertPat.setString(5, jk);
                insertPat.setString(6, nomorHp);
                insertPat.executeUpdate();
            }

            DefaultTableModel model = (DefaultTableModel) Tabeldata.getModel();
            model.setRowCount(0); // Hapus semua data dari tabel
            Tampil(); // Tampilkan ulang data dari database
            Refresh();
        } catch (Exception e) {
            e.printStackTrace();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_simpanActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
     Refresh();   // TODO add your handling code here:
    }//GEN-LAST:event_batalActionPerformed

    private void PosisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PosisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PosisiActionPerformed

    private void TabeldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabeldataMouseClicked
        Nama.setText(Tabeldata.getValueAt(Tabeldata.getSelectedRow(),1).toString());
        Alamat.setText(Tabeldata.getValueAt(Tabeldata.getSelectedRow(),2).toString());
        Posisi.setSelectedItem(Tabeldata.getValueAt(Tabeldata.getSelectedRow(),3).toString());
        NomorHp.setText(Tabeldata.getValueAt(Tabeldata.getSelectedRow(),5).toString());
        String jenisKelamin = Tabeldata.getValueAt(Tabeldata.getSelectedRow(), 4).toString();
        if (jenisKelamin.equals("Laki-laki")) {
            Laki.setSelected(true);
        } else if (jenisKelamin.equals("Perempuan")) {
            Perempuan.setSelected(true);
        } else {
            jenisKelaminGroup.clearSelection();
        } 
        
        simpan.setText("Ubah");
    }//GEN-LAST:event_TabeldataMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField Alamat;
    private javax.swing.JRadioButton Laki;
    private java.awt.TextField Nama;
    private java.awt.TextField NomorHp;
    private javax.swing.JRadioButton Perempuan;
    private javax.swing.JComboBox<String> Posisi;
    private javax.swing.JTable Tabeldata;
    private javax.swing.JButton batal;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton simpan;
    // End of variables declaration//GEN-END:variables
}
