/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaapplication1;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ButtonGroup;

/**
 *
 * @author LENOVO
 */
public class Data extends javax.swing.JPanel {
    private Statement st;
    private Connection Con;
    private ResultSet Rs;
    private String Sql="";
    private ButtonGroup jenisKelaminGroup;
    

    /**
     * Creates new form Data
     * @param rowData
     */
    public void tambahkanDataKeTabel(Object[] rowData) {
        DefaultTableModel model = (DefaultTableModel) Tabeldata.getModel();
        model.addRow(rowData);
    }
    public Data() {
        initComponents();
        displayData();
        
        jenisKelaminGroup = new ButtonGroup();
        jenisKelaminGroup.add(Laki);
        jenisKelaminGroup.add(Perempuan);
    }
    private void displayData() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbcrew", "root", "");
            Tampil(Sql);  
        } catch (Exception e) {
            System.out.println("Koneksi Gagal" + e.getMessage());
        }
    }
     private void updateData(String idKaryawan, String nama, String posisi, String jenisKelamin, String nomorHp) {
        try {
            String sql = "UPDATE tbcrew SET `Nama Karyawan`=?, `Posisi`=?, `Jenis Kelamin`=?, `Nomor HP`=? WHERE `ID Karyawan`=?";
            Connection con = (Connection) Koneksi.getConnection();
            PreparedStatement pat = con.prepareStatement(sql);
            pat.setString(1, nama);
            pat.setString(2, posisi);
            pat.setString(3, jenisKelamin);
            pat.setString(4, nomorHp);
            pat.setString(5, idKaryawan);
            pat.executeUpdate();
            
            // Update the table data
            displayData();

            JOptionPane.showMessageDialog(this, "Data berhasil diupdate.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void Tampil(String Sql) {
        DefaultTableModel kolomkolom = new DefaultTableModel();
        kolomkolom.addColumn("ID Karyawan");
        kolomkolom.addColumn("Nama Karyawan");
        kolomkolom.addColumn("Alamat");
        kolomkolom.addColumn("Posisi");
        kolomkolom.addColumn("Jenis Kelamin");
        kolomkolom.addColumn("Nomor HP");

        try {
            st = Con.createStatement();
            Rs = st.executeQuery("SELECT * FROM tbcrew");
            while (Rs.next()) {
                kolomkolom.addRow(new Object[] {
                    Rs.getString(1), Rs.getString(2), Rs.getString(3),
                    Rs.getString(4), Rs.getString(5),Rs.getString(6)});
            }
            Tabeldata.setModel(kolomkolom);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan \n" + e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Perempuan = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        edlt = new javax.swing.JButton();
        Laki = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        NomorHp = new java.awt.TextField();
        Alamat = new java.awt.TextField();
        Posisi = new java.awt.TextField();
        Nama = new java.awt.TextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabeldata = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA KARYAWAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1527, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1527, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("POSISI");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 60, 16));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NOMOR HP");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, 16));

        Perempuan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Perempuan.setForeground(new java.awt.Color(255, 255, 255));
        Perempuan.setText("Perempuan");
        Perempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerempuanActionPerformed(evt);
            }
        });
        jPanel3.add(Perempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("JENIS KELAMIN");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 110, 16));

        jButton4.setText("Refresh");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 75, -1));

        edlt.setBackground(new java.awt.Color(102, 255, 255));
        edlt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        edlt.setText("Edit Data Karyawan");
        edlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edltActionPerformed(evt);
            }
        });
        jPanel3.add(edlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 160, 30));

        Laki.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Laki.setForeground(new java.awt.Color(255, 255, 255));
        Laki.setText("Laki-laki");
        Laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LakiActionPerformed(evt);
            }
        });
        jPanel3.add(Laki, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 98, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ALAMAT");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, 16));
        jPanel3.add(NomorHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 270, -1));

        Alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatActionPerformed(evt);
            }
        });
        jPanel3.add(Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 270, -1));
        jPanel3.add(Posisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 270, -1));

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        jPanel3.add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 270, -1));

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Tambah Karyawan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 150, 30));

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Hapus data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 130, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NAMA");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 60, 16));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/1a8a1eae-5d2f-4756-b4b0-19b8389bb943.jpg"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 380));

        Tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Karyawan", "Nama Karyawan", "Posisi", "Jenis Kelamin", "Tanggal Absensi dan Waktu Absensi", "Keterangan", "Nomor HP"
            }
        )
        {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        }
    );
    jScrollPane1.setViewportView(Tabeldata);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE))
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void PerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerempuanActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Nama.setText("nama");
        Alamat.setText("alamat");
        Posisi.setText("posisi");
        NomorHp.setText("nomorHp");
        jenisKelaminGroup.clearSelection();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void edltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edltActionPerformed
        int selectedRow = Tabeldata.getSelectedRow();

        if (selectedRow != -1) {
            // Mendapatkan nilai-nilai dari baris terpilih
            String idKaryawan = Tabeldata.getValueAt(selectedRow, 0).toString();
            String nama = Tabeldata.getValueAt(selectedRow, 1).toString();
            String alamat = Tabeldata.getValueAt(selectedRow, 2).toString();
            String posisi = Tabeldata.getValueAt(selectedRow, 3).toString();
            String jenisKelamin = Tabeldata.getValueAt(selectedRow, 4).toString();
            String nomorHp = Tabeldata.getValueAt(selectedRow, 5).toString();

           // Membuat instance dari kelas TambahKaryawan dan menampilkannya
            TambahKaryawan tambahKaryawanFrame = new TambahKaryawan(this, idKaryawan, nama, alamat, posisi, jenisKelamin, nomorHp);
            tambahKaryawanFrame.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diedit terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_edltActionPerformed

    private void LakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LakiActionPerformed

    private void AlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatActionPerformed

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String jk = null;
        String idPrefix = "";

        if (Laki.isSelected()) {
            jk = "Laki-Laki";
            idPrefix = "01";
        } else if (Perempuan.isSelected()) {
            jk = "Perempuan";
            idPrefix = "02";
        }

        try {
            String nama = Nama.getText(); // Menggunakan Nama.getText() untuk mendapatkan nilai dari JTextField Nama
            String posisi = Posisi.getText(); // Menggunakan Posisi.getText() untuk mendapatkan nilai dari JTextField Posisi
            String nomorHp = NomorHp.getText();
            String alamat = Alamat.getText();// Menggunakan NomorHp.getText() untuk mendapatkan nilai dari JTextField NomorHp
            String hurufPertama = posisi.substring(0, 1).toUpperCase();
            String hurufKetiga = posisi.length() >= 3 ? posisi.substring(2, 3).toUpperCase() : "";
            String duaDigitTerakhir = nomorHp.length() >= 2 ? nomorHp.substring(nomorHp.length() - 2) : "";
            String IDKaryawan = hurufPertama + hurufKetiga + idPrefix + duaDigitTerakhir;
            Object[] rowData = {IDKaryawan, nama,alamat, posisi, jk,nomorHp};
            tambahkanDataKeTabel(rowData);

            String sql = "INSERT INTO `tbcrew`(`ID Karyawan`, `Nama Karyawan`,`Alamat`, `Posisi`, `Jenis Kelamin`, `Nomor HP`) VALUES (?, ?, ?, ?, ?, ?)";
            Connection con = (Connection) Koneksi.getConnection();
            PreparedStatement pat = con.prepareStatement(sql);
            pat.setString(1, IDKaryawan);
            pat.setString(2, nama);
            pat.setString(3, alamat);
            pat.setString(4, posisi);
            pat.setString(5, jk);
            pat.setString(6, nomorHp);
            pat.execute();

            String idKaryawanToUpdate = (String) jButton1.getClientProperty("idKaryawan");
            if (idKaryawanToUpdate != null) {
                updateData(idKaryawanToUpdate, nama, posisi, jk, nomorHp);
                jButton1.putClientProperty("idKaryawan", null); // Reset data yang akan diedit setelah pembaruan berhasil
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedRow = Tabeldata.getSelectedRow();
        if (selectedRow != -1) {
            String idKaryawan = Tabeldata.getValueAt(selectedRow, 0).toString();

            int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    String sql = "DELETE FROM tbcrew WHERE `ID Karyawan`=?";
                    Connection con = (Connection) Koneksi.getConnection();
                    PreparedStatement pat = con.prepareStatement(sql);
                    pat.setString(1, idKaryawan);
                    pat.executeUpdate();

                    // Hapus baris yang terpilih dari tabel GUI
                    DefaultTableModel model = (DefaultTableModel) Tabeldata.getModel();
                    model.removeRow(selectedRow);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField Alamat;
    private javax.swing.JRadioButton Laki;
    private java.awt.TextField Nama;
    private java.awt.TextField NomorHp;
    private javax.swing.JRadioButton Perempuan;
    private java.awt.TextField Posisi;
    private javax.swing.JTable Tabeldata;
    private javax.swing.JButton edlt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
