/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;
import javaapplication1.Koneksi;
import java.util.Date;
import java.sql.Timestamp;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.ButtonGroup;

/**
 *
 * @author LENOVO
 */
public class TambahKaryawan extends javax.swing.JFrame {
    private Data DataGUI;
    private ButtonGroup jenisKelaminGroup;
    

    public String getNama() {
        return Nama.getText();
    }

    public String getPosisi() {
        return Posisi.getText();
    }

    public String getNomorHp() {
        return NomorHp.getText();
    }
    
    public String getAlamat() {
        return Alamat.getText();
    }


    public String getJenisKelamin() {
        if (Laki.isSelected()) {
            return "Laki-Laki";
        } else if (Perempuan.isSelected()) {
            return "Perempuan";
        } else {
            return null;
        }
    }
     
    /**
     * Creates new form TambahKaryawan
     * @param DataGUI
     * @param idKaryawan
     * @param nama
     * @param alamat
     * @param posisi
     * @param jenisKelamin
     * @param nomorHp
     */
    public TambahKaryawan(Data DataGUI,String idKaryawan, String nama,String alamat, String posisi, String jenisKelamin, String nomorHp) {
        initComponents();
        this.DataGUI = DataGUI;
        setLocationRelativeTo(this);
         Nama.setText(nama);
         Posisi.setText(posisi);
         NomorHp.setText(nomorHp);
        jenisKelaminGroup = new ButtonGroup();
        jenisKelaminGroup.add(Laki);
        jenisKelaminGroup.add(Perempuan);
         
         
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NomorHp = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        Posisi = new javax.swing.JTextField();
        Alamat = new javax.swing.JTextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        jLabel5 = new javax.swing.JLabel();
        Laki = new javax.swing.JRadioButton();
        Perempuan = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UPDATE DATA KARYAWAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 396, 53));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAMA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ALAMAT");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 60, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NOMOR HP");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 80, -1));
        getContentPane().add(NomorHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 150, -1));
        getContentPane().add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 150, -1));

        Posisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PosisiActionPerformed(evt);
            }
        });
        getContentPane().add(Posisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 150, -1));

        Alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatActionPerformed(evt);
            }
        });
        getContentPane().add(Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 150, -1));

        button1.setBackground(new java.awt.Color(255, 51, 51));
        button1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button1.setLabel("Cancel");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 150, -1));

        button2.setBackground(new java.awt.Color(102, 255, 102));
        button2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button2.setLabel("Simpan");
        button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button2MouseClicked(evt);
            }
        });
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 150, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("JENIS KELAMIN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 110, -1));

        Laki.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Laki.setForeground(new java.awt.Color(255, 255, 255));
        Laki.setText("Laki-laki");
        Laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LakiActionPerformed(evt);
            }
        });
        getContentPane().add(Laki, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 98, -1));

        Perempuan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Perempuan.setForeground(new java.awt.Color(255, 255, 255));
        Perempuan.setText("Perempuan");
        Perempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerempuanActionPerformed(evt);
            }
        });
        getContentPane().add(Perempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 98, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("POSISI");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 60, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/1a8a1eae-5d2f-4756-b4b0-19b8389bb943.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 450, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PosisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PosisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PosisiActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
       this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseClicked
    String jk = null;
    String idPrefix = "";

    if (jenisKelaminGroup.getSelection() == Laki.getModel()) {
        jk = "Laki-Laki";
        idPrefix = "01";
    } else if (jenisKelaminGroup.getSelection() == Perempuan.getModel()) {
        jk = "Perempuan";
        idPrefix = "02";
    }


    try {
        String nama = Nama.getText();
        String alamat = Alamat.getText();
        String posisi = Posisi.getText();
        String nomorHp = NomorHp.getText();
        String hurufPertama = posisi.substring(0, 1).toUpperCase();
        String hurufKetiga = posisi.length() >= 3 ? posisi.substring(2, 3).toUpperCase() : "";
        String duaDigitTerakhir = nomorHp.length() >= 2 ? nomorHp.substring(nomorHp.length() - 2) : "";
        String IDKaryawan = hurufPertama + hurufKetiga + idPrefix + duaDigitTerakhir;

        String sql = "INSERT INTO `tbcrew`(`ID Karyawan`, `Nama Karyawan`, `Alamat`, `Posisi`, `Jenis Kelamin`, `Nomor HP`) VALUES (?, ?, ?, ?, ?, ?)";
        Connection con = (Connection) Koneksi.getConnection();
        PreparedStatement pat = con.prepareStatement(sql);
        pat.setString(1, IDKaryawan);
        pat.setString(2, nama);
        pat.setString(3, alamat);
        pat.setString(4, posisi);
        pat.setString(5, jk);
        pat.setString(6, nomorHp);
        pat.execute();
    } catch (Exception e) {
        e.printStackTrace();
    }

    
    // Menutup frame TambahKaryawan setelah menyimpan data
    this.dispose();
    }//GEN-LAST:event_button2MouseClicked

    private void LakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LakiActionPerformed

    private void PerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerempuanActionPerformed

    private void AlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alamat;
    private javax.swing.JRadioButton Laki;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField NomorHp;
    private javax.swing.JRadioButton Perempuan;
    private javax.swing.JTextField Posisi;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
